<?php
/**
* @file
* Módulo para probar formularios
* Este módulo crea un formulario
*/

/**
 * Implements hook_menu().
 */
function forms_forcontu_menu() {
  $items['forms_forcontu/form1'] = array(
    'title' => 'Forms Forcontu form 1',
    'description' => 'Muestra una descripción del formulario',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('forms_forcontu_form1'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['forms_forcontu/form2'] = array(
    'title' => 'Example form 2',
    'description' => 'Distintos elementos de formulario',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('forms_forcontu_form2'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['forms_forcontu/form3'] = array(
    'title' => 'Formulario personalizado',
    'description' => 'Formulario personalizado',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('forms_forcontu_form3'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
* Page callback
* Función que se invocará al cargar la página www.example.com/forms_forcontu/form1
*/
function forms_forcontu_form1($form_state) {
  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('Forms Forcontu form 1'),
  );
  $form['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
  );
  $form['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
* Page callback
* Función que se invocará al cargar la página www.example.com/forms_forcontu/form2
*/
function forms_forcontu_form2($form_state) {
  // Contenedor para pestañas verticales
  $form['tabs'] = array(
    '#type' => 'vertical_tabs',
  );
  // Bloque de información de la cuenta de usuario
  $form['tabs']['account_info'] = array(
    '#type' => 'fieldset',
    '#title' => 'Información de la cuenta',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['tabs']['account_info']['email'] = array(
    '#type' => 'textfield',
    '#title' => 'E-mail',
    '#default_value' => 'E-mail de usuario',
    '#size' => 30,
    '#maxlength' => 30,
    '#required' => TRUE,
  );
  $form['tabs']['account_info']['pass'] = array(
    '#type' => 'password_confirm',
    '#title' => t('Password'),
    '#size' => 15,
  );
  $form['tabs']['account_info']['signature'] = array(
    '#type' => 'textfield',
    '#title' => 'Tu firma',
    '#default_value' => 'Firma',
    '#size' => 30,
    '#maxlength' => 30,
  );
  //Bloque de información personal
  $form['tabs']['personal_info'] = array(
    '#type' => 'fieldset',
    '#title' => 'Información personal',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['tabs']['personal_info']['first_name'] = array(
    '#type' => 'textfield',
    '#title' => 'Nombre',
    '#required' => TRUE,
    '#default_value' => "Nombre",
    '#description' => "Escriba su nombre",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['tabs']['personal_info']['last_name'] = array(
    '#type' => 'textfield',
    '#title' => 'Apellidos',
    '#required' => TRUE,
    '#default_value' => "Apellidos",
    '#description' => "Escriba sus apellidos",
    '#size' => 40,
    '#maxlength' => 40,
  );
  $form['tabs']['personal_info']['ejemplo_imagen_fid'] = array(
    '#title' => 'Tu foto',
    '#type' => 'managed_file',
    '#description' => t('La imagen subida  será mostrada en tu perfil.' ),
    '#default_value' => variable_get('image_demo_form', ''),
    '#upload_location' => '/sites/default/files',
  );
  $form['tabs']['personal_info']['months'] = array(
    '#type' => 'select',
    '#title' => t('Month'),
    '#default_value' => 'january',
    '#options' => array(
      'january' => t('January'),
      'february' => t('February'),
      'march' => t('March'),
      'april' => t('April'),
      'may' => t('May'),
      'june' => t('June'),
      'july' => t('July'),
      'august' => t('August'),
      'september' => t('September'),
      'october' => t('October'),
      'november' => t('November'),
      'december' => t('December'),
    ),
    '#description' => t('Selecciona mes de nacimiento'),
  );
  // Bloque de información profesional
  $form['tabs']['professional_info'] = array(
    '#type' => 'fieldset',
    '#title' => 'Información profesional',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['tabs']['professional_info']['new_upload'] = array(
    '#type' => 'file',
    '#title' => 'Adjunta tu CV',
    '#size' => 40,
    '#attributes' => array('enctype' => "multipart/form-data"),
  );
  // Envío de formulario
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Enviar'),
  );

  return $form;
}

/**
* Función de envío del formulario forms_forcontu_form2
*/
function forms_forcontu_form2_submit($form, &$form_state) {
  drupal_set_message(t('<strong>Su cuenta de usuario ha sido creada correctamente.</strong>'));
  drupal_goto("");
}

/**
* Page callback
* Función que se invocará al cargar la página www.example.com/forms_forcontu/form3
*/
function forms_forcontu_form3($form_state) {
  // Contenedor para pestañas verticales
  $form['tabs'] = array(
    '#type' => 'vertical_tabs',
  );
  //Grupo de elementos datos personales
  $form['tabs']['datos_personales'] = array(
    '#type' => 'fieldset',
    '#title' => t('Datos personales'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE, 
  );
  $form['tabs']['datos_personales']['nombre'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#required' => TRUE,
    '#description' => "Escriba su nombre",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['tabs']['datos_personales']['apellidos'] = array(
    '#type' => 'textfield',
    '#title' => t('Apellidos'),
    '#required' => TRUE,
    '#description' => "Escriba sus apellidos",
    '#size' => 40,
    '#maxlength' => 40,
  );
  $form['tabs']['datos_personales']['correo_electronico'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#description' => 'Escriba su correo electrónico',
    '#size' => 30,
    '#maxlength' => 30,
  );
  $form['tabs']['datos_personales']['direccion'] = array(
    '#type' => 'textarea',
    '#title' => t('Dirección'),
    '#description' => 'Escriba su dirección',
    '#cols' => 60,
    '#rows' => 4,
  );
  $form['tabs']['datos_personales']['pais'] = array(
    '#type' => 'select',
    '#title' => t('País'),
    '#default_value' => 'españa',
    '#options' => array(
      'alemania' => 'Alemania',
      'españa' => 'España',
      'francia' => 'Francia',
      'italia' => 'Italia',
    ),
    '#description' => 'Seleccione un país',
  );
  //Grupo de datos de acceso
  $form['tabs']['datos_acceso'] = array(
    '#type' => 'fieldset',
    '#title' => t('Datos de acceso'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE, 
  );
  $form['tabs']['datos_acceso']['usuario'] = array(
    '#type' => 'textfield',
    '#title' => t('Usuario'),
    '#required' => TRUE,
    '#default_value' => "Nombre de usuario",
    '#description' => "Escriba su nombre de usuario",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['tabs']['datos_acceso']['contrasena'] = array(
    '#type' => 'password_confirm',
    '#title' => t('Password'),
    '#description' => 'Escriba la palabra de paso',
    '#size' => 15,
    '#required' => TRUE,
  );
  //añadimos el campo de selección roles
  $roles = user_roles();
  //dpm($roles);
  for ($i=1; $i <= count($roles); $i++) { 
    $roles_list[$roles[$i]] = $roles[$i];
  }
  //dpm($roles_list);
  $form['tabs']['datos_acceso']['roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Roles'),
    '#options' => $roles_list,
    '#description' => t('Select rol or roles.'),
  );
  // Envío de formulario
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Enviar',
  );

  return $form;
}

/**
* Función de envío del formulario forms_forcontu_form3
*/
function forms_forcontu_form3_submit($form, &$form_state) {
  global $user;
  $result = db_insert('forms_forcontu')
                ->fields(array(
                  'uid' => $user->uid,
                  'nombre' => $form_state['values']['nombre'],
                  'apellidos' => $form_state['values']['apellidos'],
                  'correo_electronico' => $form_state['values']['correo_electronico'],
                  'direccion' => $form_state['values']['direccion'],
                  'pais' => $form_state['values']['pais'],
                  'usuario' => $form_state['values']['usuario'],
                  'contrasena' => md5($form_state['values']['contrasena']),
                  'creado' => time(),
                ))
                ->execute();
  drupal_set_message(t('<strong>La información creada en form3 ha sido guardada correctamente.</strong>'));
  drupal_goto("");
}

/**
* Función de validación del formulario forms_forcontu_form3
*/
function forms_forcontu_form3_validate($form, &$form_state) {
  //validamos correo electrónico
  if (!valid_email_address($form_state['values']['correo_electronico'])) {
    form_set_error('correo_electronico', t('You must enter a valid e-mail address.'));
  }
  //validamos pais empieza por vocal
  if (preg_match("/[^aeiouAEIOU]/", $form_state['values']['pais'][0]) ) {
    form_set_error('pais', t('The selected country must begin with a vowel.'));
  }
  //validamos password
  if (!preg_match("/\D{1}[a-zA-Z0-9]{5,14}$/", $form_state['values']['usuario']) ) {
    form_set_error('usuario', t('The user name can only contain letters and numbers and can not begin to number. Minimun 6 and maximum 15 characters.'));
  }
  //validamos contraseña
  if (!preg_match("/((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,20})/", $form_state['values']['contrasena']) ) {
    form_set_error('contrasena', t('La contraseña debe tener entre 5 y 10 caracteres y se tiene que componer al menos de una letra en mayúsculas, una letra en minúsculas, un número y un carácter no alfanumérico.'));
  }
}